Task 1 from Patterns hw
VolhaMolochko/aqa25_onl pull request #10
Opened 2024-04-04 19:03 UTC by VolhaMolochko

ChainOfInvocations.
Остальные по мере готовности вышлю

2024-04-07 17:57 UTC, wildpioneer requested changes

2024-04-07 17:57 UTC, wildpioneer commented on src/test/java/pages/projects/AddProjectPage.java
> +    public ProjectsOverviewPage successfulProjectAdding(String projectName){
Должна быть пустая строка перед методом

2024-04-07 17:57 UTC, wildpioneer commented on src/test/java/pages/projects/AddProjectPage.java
> +    private void projectAdding(String projectName){
1. Название метода должно быть AddProject
2. Возвращаемое значение должно быть AddProjectPage

2024-04-13 23:40 UTC, VolhaMolochko commented
Поправила

2024-04-29 09:40 UTC, wildpioneer commented
Проверено

2024-04-29 09:40 UTC, closed without merging