Test ng hw
VolhaMolochko/aqa25_onl pull request #2
Opened 2024-02-25 16:01 UTC by VolhaMolochko

2024-02-26 10:01 UTC, wildpioneer requested changes

2024-02-26 10:01 UTC, wildpioneer commented on src/main/java/Calculator.java
> +    public int div1(int c, int d) throws NumberException {
Почему методы называются по разному??? Перечитать про перегрузку

2024-02-26 10:01 UTC, wildpioneer commented on src/main/java/Calculator.java
> +        if (d == 0) {
Никаких проверок в самих методах не нужно делать - все проверки будут в тестах

2024-02-26 10:01 UTC, wildpioneer commented on src/test/java/DivTwoTest.java
> +        calculator.div2(y,z);
Отсутствуют тесты на Infinity и NaN

2024-02-26 14:34 UTC, VolhaMolochko commented on src/main/java/Calculator.java
> +    public int div1(int c, int d) throws NumberException {
По условию задачи 2 метода

2024-02-26 15:39 UTC, VolhaMolochko commented
New fix.
https://github.com/VolhaMolochko/aqa25_onl/pull/2/commits/315cdcd76e35c8e805e70c0b579d2c07d9111176

2024-02-26 18:47 UTC, VolhaMolochko commented on src/main/java/Calculator.java
> +    public int div1(int c, int d) throws NumberException {
Из описания задачи кажется очевидным, что их должно быть два. 
переписала с использование полиморфизма (Имя одно, параметры разные)

2024-02-26 18:48 UTC, VolhaMolochko commented on src/main/java/Calculator.java
> +        if (d == 0) {
Убрала.

2024-02-26 18:48 UTC, VolhaMolochko commented on src/test/java/DivTwoTest.java
> +        calculator.div2(y,z);
Done

2024-03-04 11:37 UTC, wildpioneer requested changes

2024-03-04 11:37 UTC, wildpioneer commented on src/main/java/Calculator.java
> +        return (double) c / d;
Не надо выполнять преобразование типов - тут должен возвращаться int

2024-03-04 11:37 UTC, wildpioneer commented on src/test/java/DivTest.java
> +        Assert.assertEquals(Double.POSITIVE_INFINITY, calculator.div(8.7, 0), 0.0001);
Хочу видеть тесты на 
1. Negative_Infinity
2. ArithmeticException()

2024-03-04 11:37 UTC, wildpioneer commented on src/test/java/DivTest.java
> +
Отсутствуют тесты со следующими атрибутами:

1. enable
2. invocationCount, invocationTimeOut,
3. timeOut
4. dependsOnMethods
5. groups
6. @Parameters
7. priority
8. retryAnalyzer

2024-03-10 20:41 UTC, wildpioneer commented on src/main/java/Calculator.java
> +    public int div1(int c, int d) throws NumberException {
А я и не говорю что он должен быть один. Их должно быть два и называться они должны одинаково. Для этого надо повторить тему "перегрузка методов"

2024-03-20 09:27 UTC, VolhaMolochko commented on src/main/java/Calculator.java
> +    public int div1(int c, int d) throws NumberException {
Метод для int вернула. Тесты по нему я кажись не удаляла, так что должны быть на месте. Оценка устраивает.

2024-03-25 13:24 UTC, wildpioneer commented
Проверено

2024-03-25 13:24 UTC, closed without merging