Две домашние задачи по Selenium WebDriver
VolhaMolochko/aqa25_onl pull request #4
Opened 2024-03-02 17:56 UTC by VolhaMolochko

Указано было, что домашка в презентации, поэтому  ссылки брала из презентации, они не те, которы ты давал.

Использование driver.switchTo().frame(1); мне не пригодилось (может что-то не так сделала).

Примечание к задаче 2.
Тест работает, если рабочее поле находится в зоне видимости юзера (не скрыто под рекламой). Чтобы тест прошел, мне пришлось центрироватькаждый элемент, с которым работаю.

2024-03-04 11:40 UTC, wildpioneer commented
Я в лекции указывал какую именно домашку делать - ну да ладно

2024-03-04 11:46 UTC, wildpioneer requested changes

2024-03-04 11:46 UTC, wildpioneer commented on src/test/java/TaskONE.java
> +        Thread.sleep(1000);
Данная пауза не нужна

2024-03-04 11:46 UTC, wildpioneer commented on src/test/java/TaskONE.java
> +        Thread.sleep(2000);
1. Данная пауза лишняя
2. Пустые строки перед закрытием метода лишние

2024-03-04 11:46 UTC, wildpioneer commented on src/test/java/TaskTwo.java
> +        JavascriptExecutor js = (JavascriptExecutor) driver;
1. Молодец что знаешь это - но мы такого еще не учили - а значит в задаче нельзя использовать ;)
2. Для работы с рекламой надо было поставить паузу и руками ее закрыть

2024-03-04 11:46 UTC, wildpioneer commented on src/test/java/TaskTwo.java
> +        WebElement button = driver.findElement(By.xpath("/html/body/div[2]/div[2]/div/div[1]/div[3]/article/section/div[2]/div[2]/div[2]"));
Абсолютный xpath недопустим в автотестах - но ты этого еще не знаешь - поэтому не учитывает в оценку - но для информации тебе - потому как у меня тест упал

2024-03-04 14:06 UTC, VolhaMolochko commented on src/test/java/TaskONE.java
> +        Thread.sleep(2000);
Убрала

2024-03-04 14:06 UTC, VolhaMolochko commented on src/test/java/TaskONE.java
> +        Thread.sleep(1000);
Убрала

2024-03-04 14:07 UTC, VolhaMolochko commented on src/test/java/TaskTwo.java
> +        WebElement button = driver.findElement(By.xpath("/html/body/div[2]/div[2]/div/div[1]/div[3]/article/section/div[2]/div[2]/div[2]"));
Поменяла

2024-03-09 16:12 UTC, VolhaMolochko commented
В целом меня оценка устраивает.

2024-03-10 20:45 UTC, wildpioneer commented
Проверено

2024-03-10 20:45 UTC, closed without merging