Locators hw
VolhaMolochko/aqa25_onl pull request #5
Opened 2024-03-09 16:05 UTC by VolhaMolochko

Домашнее задание по локаторам.

2024-03-10 20:55 UTC, wildpioneer requested changes

2024-03-10 20:55 UTC, wildpioneer commented on src/main/resources/index.html
> +<!DOCTYPE html>
Для домашней работы данный файл не нужен

2024-03-10 20:55 UTC, wildpioneer commented on src/test/java/Task_8.java
> +        driver.findElement(By.id("finish")).click();
Отсутствуют тесты на следующие локаторы:
XPath - Поиск по тексту
XPath - Поиск по частичному совпадению текста
XPath - following
CSS - .class1.class2
CSS - .class1 .class2

2024-03-15 12:37 UTC, VolhaMolochko commented
Добавила 
XPath - Поиск по тексту
XPath - Поиск по частичному совпадению текста
XPath - following
CSS - .class1.class2

Не смогла найти для такого локатара кейс.
CSS - .class1 .class2

В целом оценка устраивает.

2024-03-25 13:24 UTC, wildpioneer commented
Проверено

2024-03-25 13:24 UTC, closed without merging