Selenium. Advanced hw
VolhaMolochko/aqa25_onl pull request #6
Opened 2024-03-17 10:32 UTC by VolhaMolochko

Привет. Оч стыдно, но сдаю поздно и не все. Доп задачу потом доделаю.
У меня не работает 3я задача, но я пока пытаюсь сама разобраться что там не так я делаю. Судя по лекции я все делаю так, выглядит как глюк идеи, но возможно и я накосячила. В 3й задаче я когда задаю путь откуда брать файл, путь находится, а когда я его пытаюсь загрузть, то он не грузится, говорит org.openqa.selenium.InvalidArgumentException: invalid argument: File not found : /C:/Users/volha/IdeaProjects/aqa25_onl/target/test-classes/Pearl.txt . 

Я уже и в папку внутри ресурса его перемещала, и саму паку ресурсов перемещала из main в test, и файл меняла и перезапускала идею, но все не помогает. У меня похожая история была, когда я делала 1е задание, но там все заработало, когда я все кинула и пошла на 2ю задачу. Пока разбираюсь, тешу себя надеждой, что саом заработает.

2024-03-18 10:42 UTC, wildpioneer requested changes

2024-03-18 10:42 UTC, wildpioneer commented on src/main/resources/config.properties
> +url=https://aqa2501.testrail.io/
Ресурсы лежат не в той папке - они у тебя в main - а должны быть в test

2024-03-20 09:28 UTC, VolhaMolochko commented on src/main/resources/config.properties
> +url=https://aqa2501.testrail.io/
перенесла

2024-03-25 13:19 UTC, wildpioneer requested changes

2024-03-25 13:19 UTC, wildpioneer commented on src/test/java/WindowsTest.java
> +        Assert.assertTrue(driver.getWindowHandles().size() == 3);
Я бы использовал Assert.assertEquals

2024-03-25 13:23 UTC, wildpioneer requested changes

2024-03-25 13:23 UTC, wildpioneer commented on src/test/java/TaskFourTest.java
> +    private boolean isFileExist(String path) {
А почему этот метод здесь, а не в WaitsService

2024-03-25 13:23 UTC, wildpioneer commented on src/test/java/TaskFourTest.java
> +        Assert.assertTrue(isFileExist("C:/Users/volha/Downloads/puppy.png"));
У меня такого пути нет

2024-03-31 08:14 UTC, VolhaMolochko commented
Подправила

2024-04-07 18:07 UTC, wildpioneer commented
Проверено

2024-04-07 18:07 UTC, closed without merging