Домашняя работа по page object
VolhaMolochko/aqa25_onl pull request #9
Opened 2024-03-30 19:32 UTC by VolhaMolochko

Я тут смотрю комиты какие-то лишние есть. Если что-то будет не так - пиши.

2024-03-31 07:59 UTC, VolhaMolochko commented
Добавила доп. задание со steps

2024-04-07 18:04 UTC, wildpioneer requested changes

2024-04-07 18:04 UTC, wildpioneer commented on src/test/java/pages/AllProductsPage.java
> +    public WebElement getProductPageName (){
Форматирование - должен быть пробел перед фигурной скобкой

2024-04-07 18:04 UTC, wildpioneer commented on src/test/java/pages/AllProductsPage.java
> +//    public void choseProduct(){
В PR не должно быть закоментированного кода

2024-04-07 18:04 UTC, wildpioneer commented on src/test/java/pages/CheckoutComplete.java
> +    private final By checkoutCompletePageNameLocator = By.cssSelector(".title");
Это CLassName

2024-04-07 18:04 UTC, wildpioneer commented on src/test/java/pages/CheckoutComplete.java
> +    private final By headerMessageLocator = By.cssSelector(".complete-header");
Это CLassName

2024-04-07 18:04 UTC, wildpioneer commented on src/test/java/pages/CheckoutComplete.java
> +    private final By messageTextLocator = By.cssSelector(".complete-text");
Это CLassName

2024-04-07 18:04 UTC, wildpioneer commented on src/test/java/pages/AllProductsPage.java
> +    private final By productPageNameLocator = By.cssSelector(".title");
Это CLassName

2024-04-14 14:52 UTC, VolhaMolochko commented
Поправила

2024-04-29 09:40 UTC, wildpioneer commented
Проверено

2024-04-29 09:40 UTC, closed without merging